version: "3"
services:
  web:
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    command: bash -c 'pm2 start app.js -i 1 --watch --no-daemon --ignore-watch="public-source tmp public views node_modules" & gulp watch'
    ports:
      - "3027:3000"
    depends_on:
      - db

    # Enable this for production
    #restart: 'always'
    #
    #
  db:
    image: mongo
    volumes:
      - ./db:/data/db
